#ifndef DXATC_UTILS_MACROS_H
#define DXATC_UTILS_MACROS_H

#ifdef __cplusplus
#define DXATC_UTILS_MACROS_CDECLS_BEGIN extern "C" {
#define DXATC_UTILS_MACROS_CDECLS_END }
#else
#define DXATC_UTILS_MACROS_CDECLS_BEGIN
#define DXATC_UTILS_MACROS_CDECLS_END
#endif

#define DXATC_UTILS_MACROS_MPS_TO_KT 1.943844492f

#define DXATC_UTILS_MACROS_SM_TO_KM 1.609344f
#define DXATC_UTILS_MACROS_KM_TO_SM 1.0f / DXATC_UTILS_MACROS_SM_TO_KM

#define DXATC_UTILS_MACROS_INHG_TO_HPA 33.86388158f
#define DXATC_UTILS_MACROS_HPA_TO_INHG 1.0f / DXATC_UTILS_MACROS_INHG_TO_HPA

#define DXATC_UTILS_MACROS_M_TO_FT 3.280839895013123f
#define DXATC_UTILS_MACROS_FT_TO_M 1.0f / DXATC_UTILS_MACROS_M_TO_FT

#define DXATC_UTILS_MACROS_NMI_TO_M 1852.0f
#define DXATC_UTILS_MACROS_NMI_TO_FT DXATC_UTILS_MACROS_NMI_TO_M * DXATC_UTILS_MACROS_M_TO_FT
#define DXATC_UTILS_MACROS_M_TO_NMI 1.0f / DXATC_UTILS_MACROS_NMI_TO_M

#define DXATC_UTILS_MACROS_DEG_TO_RAD 3.141592654f / 180.0f

#define DXATC_UTILS_MACROS_ARYSZ(ary) sizeof(ary)/sizeof(ary[0])
#endif
