#ifndef DXATC_UTILS_MACROS_H
#define DXATC_UTILS_MACROS_H

#ifdef __cplusplus
#define DXATC_UTILS_MACROS_CDECLS_BEGIN extern "C" {
#define DXATC_UTILS_MACROS_CDECLS_END }
#else
#define DXATC_UTILS_MACROS_CDECLS_BEGIN
#define DXATC_UTILS_MACROS_CDECLS_END
#endif

#define DXATC_UTILS_MACROS_MPS_TO_KT 1.943844492f
#define DXATC_UTILS_MACROS_SM_TO_KM 1.609344f
#define DXATC_UTILS_MACROS_INHG_TO_HPA 33.86388158f
#endif
